# Generated by Django 2.0.4 on 2019-06-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=120)),
                ('Detalle', models.CharField(max_length=120)),
                ('Monto_pago', models.PositiveIntegerField()),
            ],
        ),
    ]
