# Generated by Django 2.0.4 on 2020-01-13 19:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estrellas', models.PositiveIntegerField(blank=True, null=True)),
                ('Comentarios', models.CharField(blank=True, max_length=120, null=True)),
                ('Fecha', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('Hora', models.TimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('Realizada', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Historial_trabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(default=datetime.datetime.now)),
                ('Hora', models.TimeField(default=datetime.datetime.now)),
                ('tipo', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('Hora', models.TimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('Activo', models.PositiveIntegerField(default=1)),
                ('Tipo', models.PositiveIntegerField(default=1)),
                ('Contable', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Postulantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('Hora', models.TimeField(default=datetime.datetime.now)),
                ('Estado', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=120)),
                ('Detalle', models.CharField(max_length=120)),
                ('Monto_pago', models.PositiveIntegerField()),
                ('Fecha', models.DateTimeField(blank=True, null=True)),
                ('Hora', models.TimeField(blank=True, null=True)),
                ('Fecha_publicacion', models.DateTimeField(default=datetime.datetime.now)),
                ('Hora_publicacion', models.TimeField(default=datetime.datetime.now)),
                ('Fecha_vencimiento', models.DateTimeField(blank=True, null=True)),
                ('rango_etario', models.CharField(choices=[('Sin rango etario especifico', 'Sin rango etario especifico'), ('15-25', '15-25'), ('25-35', '25-35'), ('35-45', '35-45'), ('45-55', '45-55'), ('55-65', '55-65')], default='Sin rango etario especifico', max_length=20)),
                ('Imagen', models.ImageField(blank=True, null=True, upload_to='media')),
                ('Personas_requeridas', models.PositiveIntegerField(default=1)),
                ('Vacantes', models.PositiveIntegerField(default=1)),
                ('Activo', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo_acordado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('Hora', models.TimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('postulante_acordado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Publicar_trabajo.Postulantes')),
            ],
        ),
    ]
