# Generated by Django 2.0.4 on 2019-06-24 07:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0007_direccion'),
        ('Publicar_trabajo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='Area',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='Registro_fullpega.Areas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajo',
            name='Direccion',
            field=models.CharField(default=23, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajo',
            name='Fecha',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='Hora',
            field=models.TimeField(default=datetime.datetime(2019, 6, 24, 6, 59, 56, 758402)),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='rango_etario',
            field=models.CharField(choices=[('Sin rango etario especifico', 'Sin rango etario especifico'), ('15-25', '15-25'), ('25-35', '25-35'), ('35-45', '35-45'), ('45-55', '45-55'), ('55-65', '55-65')], default='Sin rango etario especifico', max_length=4),
        ),
    ]
