# Generated by Django 2.0.4 on 2020-01-13 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Publicar_trabajo', '0001_initial'),
        ('Registro_fullpega', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='Area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro_fullpega.Areas'),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='Direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro_fullpega.Direccion'),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='Usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Registro_fullpega.Persona'),
        ),
        migrations.AddField(
            model_name='postulantes',
            name='Postulante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro_fullpega.Persona'),
        ),
        migrations.AddField(
            model_name='postulantes',
            name='Trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Publicar_trabajo.Trabajo'),
        ),
        migrations.AddField(
            model_name='notificaciones',
            name='Trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Publicar_trabajo.Trabajo'),
        ),
        migrations.AddField(
            model_name='notificaciones',
            name='Trabajo_acordado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Publicar_trabajo.Trabajo_acordado'),
        ),
        migrations.AddField(
            model_name='notificaciones',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro_fullpega.Persona'),
        ),
        migrations.AddField(
            model_name='historial_trabajo',
            name='Persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro_fullpega.Persona'),
        ),
        migrations.AddField(
            model_name='historial_trabajo',
            name='Trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Publicar_trabajo.Trabajo'),
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='Pega_calificada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Publicar_trabajo.Trabajo'),
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='Registro_fullpega.Persona'),
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='usuario_calificador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_calificador', to='Registro_fullpega.Persona'),
        ),
    ]
