# Generated by Django 2.0.4 on 2019-08-05 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0002_auto_20190624_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='Hora',
            field=models.TimeField(default=datetime.datetime(2019, 8, 5, 5, 13, 45, 252933)),
        ),
    ]
