# Generated by Django 2.0.4 on 2019-08-05 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0005_auto_20190805_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='Hora',
            field=models.TimeField(default=datetime.datetime(2019, 8, 5, 5, 19, 35, 697180)),
        ),
    ]
