# Generated by Django 2.0.4 on 2019-08-06 01:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Publicar_trabajo', '0006_auto_20190805_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='Usuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='Hora',
            field=models.TimeField(default=datetime.datetime(2019, 8, 6, 1, 10, 11, 634739)),
        ),
    ]
