# Generated by Django 2.0.4 on 2019-08-06 01:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0007_auto_20190806_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='Hora',
            field=models.TimeField(default=datetime.datetime(2019, 8, 6, 1, 10, 24, 35157)),
        ),
    ]
