# Generated by Django 2.0.4 on 2019-08-06 01:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0010_auto_20190806_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='Hora',
            field=models.TimeField(default=datetime.datetime(2019, 8, 6, 1, 16, 4, 437798)),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='rango_etario',
            field=models.CharField(choices=[('Sin rango etario especifico', 'Sin rango etario especifico'), ('15-25', '15-25'), ('25-35', '25-35'), ('35-45', '35-45'), ('45-55', '45-55'), ('55-65', '55-65')], default='Sin rango etario especifico', max_length=20),
        ),
    ]
