# Generated by Django 2.0.4 on 2019-08-20 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0011_auto_20190806_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='Hora',
            field=models.TimeField(default=datetime.datetime(2019, 8, 20, 8, 46, 28, 229976)),
        ),
    ]
