# Generated by Django 2.0.4 on 2019-08-21 05:12

import Publicar_trabajo.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0013_auto_20190820_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to=Publicar_trabajo.models.content_file_name),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='Hora',
            field=models.TimeField(default=datetime.datetime(2019, 8, 21, 5, 12, 25, 9212)),
        ),
    ]
