# Generated by Django 2.0.4 on 2019-08-21 05:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0015_auto_20190821_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='Hora',
            field=models.TimeField(default=datetime.datetime(2019, 8, 21, 5, 18, 31, 695061)),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='Usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Registro_fullpega.Persona'),
        ),
    ]
