# Generated by Django 2.0.4 on 2019-08-21 05:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0016_auto_20190821_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='Area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro_fullpega.Areas'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='Direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro_fullpega.Direccion'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='Hora',
            field=models.TimeField(default=datetime.datetime(2019, 8, 21, 5, 23, 24, 320672)),
        ),
    ]
