# Generated by Django 2.0.4 on 2019-08-21 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0017_auto_20190821_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='Activo',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='Hora',
            field=models.TimeField(default=datetime.datetime(2019, 8, 21, 22, 58, 18, 334796)),
        ),
    ]
