# Generated by Django 2.0.4 on 2019-08-25 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0018_auto_20190821_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='Hora',
            field=models.TimeField(default=datetime.datetime(2019, 8, 25, 4, 16, 23, 459079)),
        ),
    ]
