# Generated by Django 2.0.4 on 2019-09-02 22:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0021_auto_20190825_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='Hora',
            field=models.TimeField(default=datetime.datetime(2019, 9, 2, 22, 31, 19, 698282)),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro_fullpega.Persona'),
        ),
    ]
