# Generated by Django 2.0.4 on 2019-09-02 22:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0022_auto_20190902_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='Hora',
            field=models.TimeField(default=datetime.datetime(2019, 9, 2, 22, 31, 30, 871473)),
        ),
    ]
