# Generated by Django 2.0.4 on 2019-09-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0023_auto_20190902_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='Fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='Hora',
            field=models.TimeField(),
        ),
    ]
