# Generated by Django 2.0.4 on 2019-09-03 05:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0012_auto_20190825_0420'),
        ('Publicar_trabajo', '0024_auto_20190903_0501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial_trabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('Hora', models.TimeField(default=datetime.datetime(2019, 9, 3, 5, 9, 35, 263695))),
                ('Persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro_fullpega.Persona')),
                ('Trabajo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Publicar_trabajo.Trabajo')),
            ],
        ),
    ]
