# Generated by Django 2.0.4 on 2019-09-03 05:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0025_historial_trabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_trabajo',
            name='Hora',
            field=models.TimeField(default=datetime.datetime(2019, 9, 3, 5, 9, 50, 910050)),
        ),
    ]
