# Generated by Django 2.0.4 on 2019-09-07 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0026_auto_20190903_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_trabajo',
            name='Hora',
            field=models.TimeField(default=datetime.datetime(2019, 9, 7, 3, 1, 45, 38799)),
        ),
    ]
