# Generated by Django 2.0.4 on 2019-09-07 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0027_auto_20190907_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_trabajo',
            name='Hora',
            field=models.TimeField(default=datetime.datetime(2019, 9, 7, 3, 49, 5, 17485)),
        ),
    ]
