# Generated by Django 2.0.4 on 2019-09-08 04:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0031_auto_20190908_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_trabajo',
            name='Hora',
            field=models.TimeField(default=datetime.datetime(2019, 9, 8, 1, 6, 40, 274923)),
        ),
    ]
