# Generated by Django 2.0.4 on 2019-09-08 04:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0032_auto_20190908_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_trabajo',
            name='Hora',
            field=models.TimeField(default=datetime.datetime(2019, 9, 8, 1, 19, 27, 285117)),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='Usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Registro_fullpega.Persona'),
        ),
    ]
