# Generated by Django 2.0.4 on 2019-09-13 23:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0035_auto_20190911_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_trabajo',
            name='Hora',
            field=models.TimeField(default=datetime.datetime(2019, 9, 13, 20, 52, 29, 388012)),
        ),
        migrations.AlterField(
            model_name='postulantes',
            name='Hora',
            field=models.TimeField(default=datetime.datetime(2019, 9, 13, 20, 52, 29, 386817)),
        ),
    ]
