# Generated by Django 2.0.4 on 2019-09-13 23:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0036_auto_20190913_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_trabajo',
            name='Hora',
            field=models.TimeField(default=datetime.datetime(2019, 9, 13, 20, 53, 5, 943207)),
        ),
        migrations.AlterField(
            model_name='postulantes',
            name='Hora',
            field=models.TimeField(default=datetime.datetime(2019, 9, 13, 20, 53, 5, 941682)),
        ),
    ]
