# Generated by Django 2.0.4 on 2019-09-27 03:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0019_auto_20190913_2052'),
        ('Publicar_trabajo', '0039_auto_20190918_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estrellas', models.PositiveIntegerField()),
                ('Comentarios', models.CharField(max_length=120)),
                ('Fecha', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('Hora', models.TimeField(default=datetime.datetime(2019, 9, 27, 0, 12, 37, 673640))),
                ('Pega_calificada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Publicar_trabajo.Trabajo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='Registro_fullpega.Persona')),
                ('usuario_calificador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_calificador', to='Registro_fullpega.Persona')),
            ],
        ),
        migrations.AlterField(
            model_name='historial_trabajo',
            name='Hora',
            field=models.TimeField(default=datetime.datetime(2019, 9, 27, 0, 12, 37, 675102)),
        ),
        migrations.AlterField(
            model_name='postulantes',
            name='Hora',
            field=models.TimeField(default=datetime.datetime(2019, 9, 27, 0, 12, 37, 670824)),
        ),
        migrations.AlterField(
            model_name='trabajo_acordado',
            name='Hora',
            field=models.TimeField(default=datetime.datetime(2019, 9, 27, 0, 12, 37, 672504)),
        ),
    ]
