# Generated by Django 2.0.4 on 2019-09-27 03:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0040_auto_20190927_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciones',
            name='Hora',
            field=models.TimeField(default=datetime.datetime(2019, 9, 27, 0, 13, 44, 47026)),
        ),
        migrations.AlterField(
            model_name='historial_trabajo',
            name='Hora',
            field=models.TimeField(default=datetime.datetime(2019, 9, 27, 0, 13, 44, 48961)),
        ),
        migrations.AlterField(
            model_name='postulantes',
            name='Hora',
            field=models.TimeField(default=datetime.datetime(2019, 9, 27, 0, 13, 44, 44118)),
        ),
        migrations.AlterField(
            model_name='trabajo_acordado',
            name='Hora',
            field=models.TimeField(default=datetime.datetime(2019, 9, 27, 0, 13, 44, 45684)),
        ),
    ]
