# Generated by Django 2.0.4 on 2019-09-27 03:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0042_auto_20190927_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciones',
            name='Hora',
            field=models.TimeField(default=datetime.datetime(2019, 9, 27, 0, 22, 34, 262862)),
        ),
        migrations.AlterField(
            model_name='historial_trabajo',
            name='Fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='historial_trabajo',
            name='Hora',
            field=models.TimeField(default=datetime.datetime(2019, 9, 27, 0, 22, 34, 265311)),
        ),
        migrations.AlterField(
            model_name='postulantes',
            name='Fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='postulantes',
            name='Hora',
            field=models.TimeField(default=datetime.datetime(2019, 9, 27, 0, 22, 34, 259732)),
        ),
        migrations.AlterField(
            model_name='trabajo_acordado',
            name='Fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='trabajo_acordado',
            name='Hora',
            field=models.TimeField(default=datetime.datetime(2019, 9, 27, 0, 22, 34, 261268)),
        ),
    ]
