# Generated by Django 2.0.4 on 2019-09-27 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0043_auto_20190927_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciones',
            name='Hora',
            field=models.TimeField(default=datetime.datetime(2019, 9, 27, 0, 24, 52, 140047)),
        ),
        migrations.AlterField(
            model_name='historial_trabajo',
            name='Hora',
            field=models.TimeField(default=datetime.datetime(2019, 9, 27, 0, 24, 52, 141428)),
        ),
        migrations.AlterField(
            model_name='postulantes',
            name='Hora',
            field=models.TimeField(default=datetime.datetime(2019, 9, 27, 0, 24, 52, 137414)),
        ),
        migrations.AlterField(
            model_name='trabajo_acordado',
            name='Hora',
            field=models.TimeField(default=datetime.datetime(2019, 9, 27, 0, 24, 52, 138962)),
        ),
    ]
