# Generated by Django 2.0.4 on 2019-09-27 03:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0047_auto_20190927_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciones',
            name='Fecha',
            field=models.DateField(default=datetime.date(2019, 9, 27)),
        ),
        migrations.AlterField(
            model_name='calificaciones',
            name='Hora',
            field=models.TimeField(default=datetime.datetime(2019, 9, 27, 0, 36, 50, 743371)),
        ),
        migrations.AlterField(
            model_name='postulantes',
            name='Fecha',
            field=models.DateField(default=datetime.date(2019, 9, 27)),
        ),
        migrations.AlterField(
            model_name='postulantes',
            name='Hora',
            field=models.TimeField(default=datetime.datetime(2019, 9, 27, 0, 36, 50, 739887)),
        ),
        migrations.AlterField(
            model_name='trabajo_acordado',
            name='Fecha',
            field=models.DateField(default=datetime.date(2019, 9, 27)),
        ),
        migrations.AlterField(
            model_name='trabajo_acordado',
            name='Hora',
            field=models.TimeField(default=datetime.datetime(2019, 9, 27, 0, 36, 50, 741653)),
        ),
    ]
