# Generated by Django 2.0.4 on 2019-09-27 03:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0049_auto_20190927_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciones',
            name='Hora',
            field=models.TimeField(default=datetime.datetime(2019, 9, 27, 0, 42, 16, 133553)),
        ),
        migrations.AlterField(
            model_name='postulantes',
            name='Hora',
            field=models.TimeField(default=datetime.datetime(2019, 9, 27, 0, 42, 16, 129911)),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='Fecha',
            field=models.DateField(null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='Hora',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='trabajo_acordado',
            name='Hora',
            field=models.TimeField(default=datetime.datetime(2019, 9, 27, 0, 42, 16, 131537)),
        ),
    ]
