# Generated by Django 2.0.4 on 2019-09-27 03:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0051_auto_20190927_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciones',
            name='Fecha',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='historial_trabajo',
            name='Fecha',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='postulantes',
            name='Fecha',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='Fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trabajo_acordado',
            name='Fecha',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
