# Generated by Django 2.0.4 on 2019-09-30 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0053_auto_20190927_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciones',
            name='Fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='calificaciones',
            name='Hora',
            field=models.TimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='Fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='Hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trabajo_acordado',
            name='Fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='trabajo_acordado',
            name='Hora',
            field=models.TimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
