# Generated by Django 2.0.4 on 2019-09-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0054_auto_20190930_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial_trabajo',
            name='tipo',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
