# Generated by Django 2.0.4 on 2019-10-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0057_auto_20191004_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='Personas_requeridas',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
