# Generated by Django 2.0.4 on 2019-10-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0058_trabajo_personas_requeridas'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='Vacantes',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
