# Generated by Django 2.0.4 on 2019-10-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0059_trabajo_vacantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciones',
            name='Realizada',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='calificaciones',
            name='Comentarios',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='calificaciones',
            name='Estrellas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
