# Generated by Django 2.0.4 on 2019-10-29 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0060_auto_20191026_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificaciones',
            name='Tipo',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
