# Generated by Django 2.0.4 on 2019-10-29 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0061_notificaciones_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificaciones',
            name='Trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Publicar_trabajo.Trabajo'),
        ),
    ]
