# Generated by Django 2.0.4 on 2019-11-29 03:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0066_auto_20191128_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='Fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='Fecha_publicacion',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
