# Generated by Django 2.0.4 on 2019-12-02 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0067_auto_20191129_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulantes',
            name='Fecha',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
