# Generated by Django 2.0.4 on 2020-01-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicar_trabajo', '0068_auto_20191202_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificaciones',
            name='Contable',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
