version: "3.0"

services:
  fullpega:
    build: .
    image: fullpegaimage
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0:8002"
    volumes:
      - .:/code
    ports:
      - "8002:8002"

  migrate:
    image: fullpegaimage
    command: python manage.py migrate
    volumes:
      - .:/code
networks:
  default:
    external:
      name: red-uwu
