version: "3.0"

services:
  fullpega:
    build: .
    image: fullpegaimage
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"

  migrate:
    image: fullpegaimage
    command: python manage.py migrate
    volumes:
      - .:/code
networks:
  default:
    external:
      name: red-uwu
