# Generated by Django 2.0.4 on 2019-12-02 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('significant', models.BooleanField()),
                ('trait_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentile', models.DecimalField(decimal_places=2, max_digits=16)),
                ('raw_score', models.DecimalField(decimal_places=2, max_digits=16)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensibilidad_watson.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Pillar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pillar_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('significant', models.BooleanField()),
                ('trait_id', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensibilidad_watson.Category')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoryResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentile', models.DecimalField(decimal_places=2, max_digits=16)),
                ('raw_score', models.DecimalField(decimal_places=2, max_digits=16)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensibilidad_watson.SubCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('word_count', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('processed_language', models.CharField(max_length=2)),
                ('json_response', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='subcategoryresult',
            name='summary',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sensibilidad_watson.Summary'),
        ),
        migrations.AddField(
            model_name='categoryresult',
            name='summary',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sensibilidad_watson.Summary'),
        ),
        migrations.AddField(
            model_name='category',
            name='pillar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensibilidad_watson.Pillar'),
        ),
    ]
