# Generated by Django 2.0.4 on 2019-12-06 23:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensibilidad_watson', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
