# Generated by Django 2.0.4 on 2019-12-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensibilidad_watson', '0002_auto_20191206_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='tipo',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
