# Generated by Django 2.0.4 on 2020-01-13 19:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Calle', models.CharField(blank=True, max_length=100, null=True)),
                ('Numero_de_calle', models.CharField(blank=True, max_length=100, null=True)),
                ('Principal', models.IntegerField(default=1)),
                ('Comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Registro_fullpega.Comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Historico_watson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Puntaje', models.IntegerField(default=0)),
                ('Label', models.CharField(blank=True, max_length=120, null=True)),
                ('Fecha', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('Hora', models.TimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('Rut', models.CharField(blank=True, max_length=20, null=True)),
                ('Imagen', models.ImageField(blank=True, null=True, upload_to='media')),
                ('Telefono_C', models.CharField(blank=True, max_length=50, null=True)),
                ('Correo', models.CharField(blank=True, max_length=100, null=True)),
                ('Fecha_nacimiento', models.DateField(default=datetime.datetime(2020, 1, 13, 16, 32, 30, 399990))),
                ('Facebook', models.CharField(blank=True, max_length=120, null=True)),
                ('Twitter', models.CharField(blank=True, max_length=120, null=True)),
                ('Linkedin', models.CharField(blank=True, max_length=120, null=True)),
                ('Instagram', models.CharField(blank=True, max_length=120, null=True)),
                ('Puntaje_watson', models.IntegerField(default=0)),
                ('Label_watson', models.CharField(blank=True, max_length=120, null=True)),
                ('Estrellas', models.CharField(blank=True, max_length=120, null=True)),
                ('Descripcion_propia', models.TextField()),
                ('privilegios', models.IntegerField(default=1)),
                ('Fecha_registro', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Preferencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M_minimo', models.IntegerField(default=1)),
                ('M_maximo', models.IntegerField(default=1000000000)),
                ('Fecha_registro', models.DateTimeField(default=datetime.datetime.now)),
                ('Area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Registro_fullpega.Areas')),
                ('Comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Registro_fullpega.Comuna')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro_fullpega.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='historico_watson',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro_fullpega.Persona'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='Persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro_fullpega.Persona'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro_fullpega.Region'),
        ),
    ]
