# Generated by Django 2.0.4 on 2018-11-09 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=120)),
                ('Modelo', models.CharField(max_length=120)),
                ('Color', models.CharField(max_length=120)),
                ('Aro', models.CharField(max_length=120)),
                ('Estado', models.CharField(max_length=120)),
                ('Tipo', models.CharField(max_length=120)),
                ('Codigo', models.CharField(max_length=120)),
                ('Monto_garantia', models.PositiveIntegerField()),
                ('Imagen', models.ImageField(upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=120)),
                ('Fecha_nacimiento', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
                ('Direccion', models.CharField(max_length=60)),
                ('rut', models.CharField(max_length=8)),
                ('dv', models.PositiveIntegerField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
