# Generated by Django 2.0.4 on 2019-03-05 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bicicleta',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
