# Generated by Django 2.0.4 on 2019-05-07 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0002_auto_20190305_0635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='privilegio',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cliente',
            name='Areas_interes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Registro_fullpega.Areas'),
            preserve_default=False,
        ),
    ]
