# Generated by Django 2.0.4 on 2019-05-13 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0004_auto_20190509_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Areas_interes',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='Registro_fullpega.Areas'),
        ),
    ]
