# Generated by Django 2.0.4 on 2019-06-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0006_auto_20190513_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=120)),
                ('comuna', models.CharField(max_length=120)),
                ('numero', models.PositiveIntegerField()),
                ('Pais', models.CharField(max_length=120)),
                ('Block_depto', models.CharField(max_length=120)),
            ],
        ),
    ]
