# Generated by Django 2.0.4 on 2019-08-05 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0008_auto_20190805_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='Direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro_fullpega.Direccion'),
        ),
    ]
