# Generated by Django 2.0.4 on 2019-08-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0009_auto_20190805_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='Fecha_nacimiento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
