# Generated by Django 2.0.4 on 2019-08-25 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0011_auto_20190825_0416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='Instragram',
            new_name='Instagram',
        ),
    ]
