# Generated by Django 2.0.4 on 2019-09-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0012_auto_20190825_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='privilegios',
            field=models.IntegerField(default=1),
        ),
    ]
