# Generated by Django 2.0.4 on 2019-09-08 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0014_auto_20190907_0349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='id',
        ),
        migrations.AlterField(
            model_name='persona',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
