# Generated by Django 2.0.4 on 2019-09-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0017_auto_20190908_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
