# Generated by Django 2.0.4 on 2019-09-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0023_auto_20190927_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='Fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
