# Generated by Django 2.0.4 on 2019-09-27 04:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0025_auto_20190927_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='Fecha_nacimiento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
