# Generated by Django 2.0.4 on 2019-09-27 04:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0027_auto_20190927_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='Fecha_nacimiento',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
