# Generated by Django 2.0.4 on 2019-09-27 04:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0031_auto_20190927_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='Fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2019, 9, 27, 1, 13, 1, 599712)),
        ),
    ]
