# Generated by Django 2.0.4 on 2019-09-30 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0035_auto_20190930_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='Fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2019, 9, 30, 4, 3, 10, 893606)),
        ),
    ]
