# Generated by Django 2.0.4 on 2019-10-04 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0036_auto_20190930_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='Fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2019, 10, 4, 15, 51, 8, 70684)),
        ),
    ]
