# Generated by Django 2.0.4 on 2019-10-04 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0037_auto_20191004_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='Fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2019, 10, 4, 16, 2, 53, 995681)),
        ),
    ]
