# Generated by Django 2.0.4 on 2019-10-13 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0038_auto_20191004_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='Fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2019, 10, 13, 19, 41, 34, 387044)),
        ),
    ]
