# Generated by Django 2.0.4 on 2019-10-29 02:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0041_auto_20191026_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='Fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2019, 10, 28, 23, 16, 5, 75339)),
        ),
    ]
