# Generated by Django 2.0.4 on 2019-10-29 02:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0042_auto_20191028_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='Fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2019, 10, 28, 23, 23, 40, 193787)),
        ),
    ]
