# Generated by Django 2.0.4 on 2019-10-30 05:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0043_auto_20191028_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='Fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2019, 10, 30, 2, 3, 56, 654940)),
        ),
    ]
