# Generated by Django 2.0.4 on 2019-11-08 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0046_auto_20191030_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='Fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2019, 11, 8, 4, 30, 27, 663098)),
        ),
    ]
