# Generated by Django 2.0.4 on 2019-11-11 02:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('Registro_fullpega', '0047_auto_20191108_0430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico_watson',
            fields=[
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Puntaje', models.IntegerField(default=0)),
                ('Label', models.CharField(blank=True, max_length=120, null=True)),
                ('Fecha', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('Hora', models.TimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='Puntaje_watson',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='persona',
            name='Fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2019, 11, 10, 23, 53, 26, 144102)),
        ),
    ]
