# Generated by Django 2.0.4 on 2019-11-11 03:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0050_auto_20191110_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='Label_watson',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='Fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2019, 11, 11, 0, 34, 47, 86889)),
        ),
    ]
