# Generated by Django 2.0.4 on 2019-11-11 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0051_auto_20191111_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='Estrellas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='persona',
            name='Fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2019, 11, 11, 1, 46, 52, 746909)),
        ),
    ]
