# Generated by Django 2.0.4 on 2019-11-11 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0052_auto_20191111_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='Estrellas',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='Fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2019, 11, 11, 1, 48, 20, 11217)),
        ),
    ]
