# Generated by Django 2.0.4 on 2019-11-11 04:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0053_auto_20191111_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico_watson',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Registro_fullpega.Persona'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='Fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2019, 11, 11, 1, 59, 29, 998711)),
        ),
    ]
