# Generated by Django 2.0.4 on 2019-11-14 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0059_auto_20191113_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comuna',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='name',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='persona',
            name='Fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2019, 11, 14, 3, 1, 59, 444481)),
        ),
    ]
