# Generated by Django 2.0.4 on 2019-11-14 22:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0060_auto_20191114_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='Direccion',
        ),
        migrations.AddField(
            model_name='direccion',
            name='Persona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Registro_fullpega.Persona'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direccion',
            name='Principal',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='persona',
            name='Fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2019, 11, 14, 19, 38, 3, 273422)),
        ),
    ]
