# Generated by Django 2.0.4 on 2019-11-14 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0061_auto_20191114_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='Ciudad',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='Pais',
        ),
        migrations.AlterField(
            model_name='persona',
            name='Fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2019, 11, 14, 19, 41, 18, 661016)),
        ),
    ]
