# Generated by Django 2.0.4 on 2019-11-14 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0062_auto_20191114_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='Fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2019, 11, 14, 19, 44, 24, 442230)),
        ),
    ]
