# Generated by Django 2.0.4 on 2019-11-16 02:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0063_auto_20191114_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='Fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2019, 11, 15, 23, 33, 18, 5390)),
        ),
    ]
