# Generated by Django 2.0.4 on 2019-11-28 23:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0064_auto_20191115_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='Fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2019, 11, 28, 20, 13, 24, 529382)),
        ),
    ]
