# Generated by Django 2.0.4 on 2019-11-29 03:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0065_auto_20191128_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='Fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2019, 11, 29, 0, 8, 16, 579560)),
        ),
    ]
