# Generated by Django 2.0.4 on 2019-12-02 03:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0066_auto_20191129_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='Fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2019, 12, 2, 0, 6, 12, 99909)),
        ),
    ]
