# Generated by Django 2.0.4 on 2019-12-02 03:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0067_auto_20191202_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='Fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2019, 12, 2, 0, 8, 25, 614279)),
        ),
    ]
