# Generated by Django 2.0.4 on 2019-12-02 03:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0068_auto_20191202_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='Fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2019, 12, 2, 0, 12, 35, 749270)),
        ),
    ]
