# Generated by Django 2.0.4 on 2019-12-02 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0069_auto_20191202_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='Fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2019, 12, 2, 16, 46, 53, 318188)),
        ),
    ]
