# Generated by Django 2.0.4 on 2019-12-06 23:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0071_auto_20191206_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='Fecha_registro',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='persona',
            name='Fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2019, 12, 6, 20, 16, 4, 480526)),
        ),
    ]
