# Generated by Django 2.0.4 on 2019-12-20 04:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0072_auto_20191206_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='Fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2019, 12, 20, 1, 49, 39, 928115)),
        ),
    ]
