# Generated by Django 2.0.4 on 2019-12-25 19:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0073_auto_20191220_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_minimo', models.IntegerField(default=1)),
                ('m_maximo', models.IntegerField(default=1000000000)),
                ('Fecha_registro', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterField(
            model_name='persona',
            name='Fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2019, 12, 25, 16, 40, 58, 466032)),
        ),
        migrations.AddField(
            model_name='preferencias',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro_fullpega.Persona'),
        ),
        migrations.AddField(
            model_name='preferencias',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro_fullpega.Direccion'),
        ),
    ]
