# Generated by Django 2.0.4 on 2019-12-25 19:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0074_auto_20191225_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferencias',
            old_name='m_maximo',
            new_name='M_maximo',
        ),
        migrations.RenameField(
            model_name='preferencias',
            old_name='m_minimo',
            new_name='M_minimo',
        ),
        migrations.RemoveField(
            model_name='preferencias',
            name='direccion',
        ),
        migrations.AddField(
            model_name='preferencias',
            name='Area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Registro_fullpega.Areas'),
        ),
        migrations.AddField(
            model_name='preferencias',
            name='Mireccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Registro_fullpega.Direccion'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='Fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2019, 12, 25, 16, 58, 52, 426236)),
        ),
    ]
