# Generated by Django 2.0.4 on 2020-01-12 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0077_auto_20200109_1058'),
        ('Registro_fullpega', '0077_auto_20200112_0229'),
    ]

    operations = [
    ]
