# Generated by Django 2.0.4 on 2020-01-12 06:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro_fullpega', '0078_merge_20200112_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='Fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2020, 1, 12, 3, 10, 24, 637769)),
        ),
    ]
